export default localSdkComponentMap;
declare namespace localSdkComponentMap {
    export { FieldCheckbox as Checkbox };
    export { FieldTextInput as TextInput };
    export { FieldDate as Date };
    export { CheckAnswers as HMRC_ODX_CheckAnswers };
    export { ChangeLink as HMRC_ODX_ChangeLink };
    export { MimicASentence as HMRC_ODX_MimicASentence };
    export { FieldRadioButtons as RadioButtons };
    export { TemplateDefaultForm as DefaultForm };
    export { InfraAssignment as Assignment };
    export { InfraAssignmentCard as AssignmentCard };
    export { InfraActionButtons as ActionButtons };
    export { InfraFlowContainer as FlowContainer };
    export { FieldPhone as HMRC_ODX_PhoneNumber };
    export { InfraView as View };
    export { TemplateCaseView as CaseView };
    export { FieldDropdown as Dropdown };
    export { TemplateFieldGroupTemplate as Group };
    export { TemplateDetails as Details };
    export { InfraViewContainer as ViewContainer };
    export { RichText };
    export { HmrcOdxGdsInfoPanel as HMRC_ODX_GDSInfoPanel };
    export { HmrcOdxGdsSummaryCard as HMRC_ODX_GDSSummaryCard };
    export { HmrcOdxGdsButton as HMRC_ODX_GDSButton };
    export { HmrcOdxComplexQuestionExplanation as HMRC_ODX_ComplexQuestionExplanation };
    export { AutoComplete };
    export { HmrcOdxGdsTextPresentation as HMRC_ODX_GDSTextPresentation };
    export { HmrcOdxGdsTaskListTemplate as HMRC_ODX_GDSTaskListTemplate };
    export { HmrcOdxSectionBased as HMRC_ODX_sectionBased };
    export { HmrcOdxGdsCheckAnswersPage as HMRC_ODX_GDSCheckAnswersPage };
    export { SimpleTableManual };
    export { HmrcOdxExtendedDate as HMRC_ODX_ExtendedDate };
}
import FieldCheckbox from "./src/components/override-sdk/field/Checkbox/";
import FieldTextInput from "./src/components/override-sdk/field/TextInput/";
import FieldDate from "./src/components/override-sdk/field/Date/";
import CheckAnswers from "./src/components/custom-sdk/template/CheckAnswers/";
import ChangeLink from "./src/components/custom-sdk/field/ChangeLink/";
import MimicASentence from "./src/components/custom-sdk/template/MimicASentence/";
import FieldRadioButtons from "./src/components/override-sdk/field/RadioButtons/";
import TemplateDefaultForm from "./src/components/override-sdk/template/DefaultForm/";
import InfraAssignment from "./src/components/override-sdk/infra/Assignment/";
import InfraAssignmentCard from "./src/components/override-sdk/infra/AssignmentCard/";
import InfraActionButtons from "./src/components/override-sdk/infra/ActionButtons/";
import InfraFlowContainer from "./src/components/override-sdk/infra/FlowContainer/";
import FieldPhone from "./src/components/override-sdk/field/Phone/";
import InfraView from "./src/components/override-sdk/infra/View/";
import TemplateCaseView from "./src/components/override-sdk/template/CaseView/";
import FieldDropdown from "./src/components/override-sdk/field/Dropdown/";
import TemplateFieldGroupTemplate from "./src/components/override-sdk/template/FieldGroupTemplate/";
import TemplateDetails from "./src/components/override-sdk/template/Details/";
import InfraViewContainer from "./src/components/override-sdk/infra/ViewContainer/";
import RichText from "./src/components/override-sdk/field/RichText/";
import HmrcOdxGdsInfoPanel from "./src/components/custom-sdk/template/HMRC_ODX_GDSInfoPanel/";
import HmrcOdxGdsSummaryCard from "./src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/";
import HmrcOdxGdsButton from "./src/components/custom-sdk/field/HMRC_ODX_GDSButton/";
import HmrcOdxComplexQuestionExplanation from "./src/components/custom-sdk/field/HMRC_ODX_ComplexQuestionExplanation/";
import AutoComplete from "./src/components/override-sdk/field/AutoComplete/";
import HmrcOdxGdsTextPresentation from "./src/components/custom-sdk/field/HMRC_ODX_GDSTextPresentation/";
import HmrcOdxGdsTaskListTemplate from "./src/components/custom-sdk/template/HMRC_ODX_GDSTaskListTemplate/";
import HmrcOdxSectionBased from "./src/components/custom-sdk/template/HMRC_ODX_sectionBased/";
import HmrcOdxGdsCheckAnswersPage from "./src/components/custom-sdk/template/HMRC_ODX_GDSCheckAnswersPage/";
import SimpleTableManual from "./src/components/override-sdk/template/SimpleTableManual/";
import HmrcOdxExtendedDate from "./src/components/custom-sdk/template/HMRC_ODX_ExtendedDate/";
